# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tankertop < Formula
  desc "btop-style terminal dashboard for Kubernetes and Docker, monitorable over SSH with no install."
  homepage "https://github.com/tankertop/tankertop"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tankertop/tankertop/releases/download/v0.1.2/tankertop_0.1.2_darwin_amd64.tar.gz"
      sha256 "f833e9fcdfefccc6c3685f4157d86a296465a896b1f15a9276ca8dae13b13b5a"

      define_method(:install) do
        bin.install "tankertop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tankertop/tankertop/releases/download/v0.1.2/tankertop_0.1.2_darwin_arm64.tar.gz"
      sha256 "60de6ca60f2bbcb62d4b959e956e6effded3a1de017a078beb38adf5630f6fde"

      define_method(:install) do
        bin.install "tankertop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tankertop/tankertop/releases/download/v0.1.2/tankertop_0.1.2_linux_amd64.tar.gz"
      sha256 "ddcc2ac6ae232ab62fed7aa23c8f15090afc8a1addf9a56846001665978d33d9"
      define_method(:install) do
        bin.install "tankertop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tankertop/tankertop/releases/download/v0.1.2/tankertop_0.1.2_linux_arm64.tar.gz"
      sha256 "92444a719330d7b369cddd4fbb74918069d3860075f3407a1ca842b284474366"
      define_method(:install) do
        bin.install "tankertop"
      end
    end
  end

  test do
    system "#{bin}/tankertop", "--version"
  end
end
